### ISSUE TITLE
如何映射目录配置 证书呢?

### ISSUE THREAD

**Issue by Dev-Wiki** [stilleshan/frpc#21]
客户端安装如下:
```yaml
version: "3"
services:
    frps:
        restart: always
        network_mode: host
        volumes:
            - /share/Docker/frpc-base/frpc.toml:/frp/frpc.toml
        container_name: frpc-base
        image: stilleshan/frpc:0.57.0
```

配置如下:
```
[[proxies]]
name = "nas"
type = "https"
localIP = "127.0.0.1"
localPort = 5000
customDomains = ["nas.devwiki.net"]


[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:5000"
# HTTPS 证书相关的配置
keyPath = "./nas.devwiki.net.key"
crtPath = "./nas.devwiki.net.crt"
hostHeaderRewrite = "nas.devwiki.net"
requestHeaders.set.x-from-where = "frp"
requestHeaders.set.x-forwarded-protol = "https"
requestHeaders.set.x-forwarded-port = "443"
```

![image](https://github.com/stilleshan/frpc/assets/12946956/30e38cc8-4ff1-4a36-9066-3296a9d56fa3)

运行后提示无法找到证书文件, 如何映射文件夹呢?

frpc-base  | 2024-04-23 22:48:51.406 [W] [client/control.go:168] [a489dea5b830a67f] [nas] start error: gen TLS config error: open ./nas.devwiki.net.crt: no such file or directory

**Comment by Dev-Wiki** [comment]
修改 目录映射:
```yaml
version: "3"
services:
    frps:
        restart: always
        network_mode: host
        volumes:
            - /share/Docker/frpc-base/frpc.toml:/frp/frpc.toml
            - /share/Docker/frpc-base/ssl/:/frp/ssl/
        container_name: frpc-base
        image: stilleshan/frpc:0.57.0
```

能看到证书文件, 修改客户端配置:
```
# HTTPS 证书相关的配置
keyPath = "./ssl/nas.devwiki.net.key"
crtPath = "./ssl/nas.devwiki.net.crt"
```

仍然提示无法找到文件
![image](https://github.com/stilleshan/frpc/assets/12946956/d65d7af9-cd21-4f23-9dda-5edb8c5456d0)

2024-04-23 22:56:51.724 [W] [client/control.go:168] [2354c02ba0a4e978] [nas] start error: gen TLS config error: open ./ssl/nas.devwiki.net.crt: no such file or directory
